# Generated by Django 4.2.2 on 2023-06-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usertrainerapp', '0002_trainingmodule_user_team_leader_reiew_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, default='User', related_name='users', to='auth.group'),
        ),
    ]
