# Generated by Django 4.2.2 on 2023-06-18 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usertrainerapp', '0006_alter_otp_user_alter_review_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingmodule',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to=settings.AUTH_USER_MODEL),
        ),
    ]
