# Generated by Django 4.2.2 on 2023-06-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertrainerapp', '0007_trainingmodule_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
