# Generated by Django 4.2.2 on 2023-06-18 11:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertrainerapp', '0008_alter_review_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingmodule',
            name='user',
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='user',
            field=models.ManyToManyField(related_name='modules', to=settings.AUTH_USER_MODEL),
        ),
    ]
