# Generated by Django 4.2.2 on 2023-06-18 13:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertrainerapp', '0009_remove_trainingmodule_user_trainingmodule_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingmodule',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='modules', to=settings.AUTH_USER_MODEL),
        ),
    ]
